src/Entity/Patients.php
<?php

namespace App\Entity;


use App\Entity\Programmes;
use App\Entity\Commandemedicaments;
use App\Repository\PatientsRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Dossiermedical;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Rendezvous;
use ApiPlatform\Core\Annotation\ApiResource;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
 
use Doctrine\ORM\Mapping\JoinColumn;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
 
#[ApiResource]
#[Vich\Uploadable]
#[ORM\Table(name:"hh_patients")]
#[ORM\Entity(repositoryClass: PatientsRepository::class)]

class Patients  implements \JsonSerializable, UserInterface, PasswordAuthenticatedUserInterface{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
    
    #[ORM\Column(name:"age", type:"integer", nullable:true)]     
    private $age;
     
    #[ORM\Column(type:"string", length:255,nullable:true)]      
    protected $image;

    #[Vich\UploadableField(mapping:"patients_images", fileNameProperty:"image")]     
    protected $imageFile;
   
    #[ORM\OneToMany(targetEntity:"App\Entity\Rendezvous",  mappedBy:"patient")]      
    private $rendezvous;
    
    #[ORM\OneToOne(targetEntity:"App\Entity\Dossiermedical", cascade:["persist"])]      
    private $dossiermedical;

    #[ORM\Column(name:"profession", type:"string",nullable:true)]     
    private $profession;

    #[ORM\Column(name:"statutmatrimonial", type:"string",nullable:true)]     
    private $statutmatrimonial;

    #[ORM\Column(name:"valide", type:"boolean")]     
    protected $valide = false;

    #[ORM\Column(type:"string",nullable:true)]      
    protected $nomComplet;
    
    #[ORM\Column(name:"sexe", type:"string", length:255,nullable:true)]     
    protected $sexe;

    #[ORM\Column(name:"nom", type:"string", length:255,nullable:true)]     
    protected $nom;

    #[ORM\Column(name:"prenom", type:"string", length:255,nullable:true)] 
    #[Assert\NotBlank()]    
    protected $prenom;
 
    #[ORM\Column(type:"string")]
     #[Assert\NotBlank()]
     #[Assert\Length(min:4, minMessage:"votre pseudo doit faire au moins 4 caractères.")]      
    private $username;
 
    #[ORM\Column(type:"string", unique:true,nullable:true)] 
    #[Assert\Email()]     
    private $email;
 
    #[ORM\Column(type:"string", length:64)]
    #[Assert\Length(min:4, minMessage:"Votre mot de passe doit faire au moins 4 caractères.")]     
    private $password;
    
    #[ORM\Column(name:"adresse", type:"text",nullable:true)]    
    protected $adresse;

    #[ORM\Column(name:"zip_code", type:"string", length:255,nullable:true)]   
    protected $zipCode;

    #[ORM\Column(name:"ville", type:"string", length:255,nullable:true)]      
    protected $ville;

    #[ORM\Column(name:"pays", type:"string", length:255,nullable:true)]    
    protected $pays;

    #[ORM\Column(name:"type", type:"string", length:255,nullable:true)]      
    protected $type = "patient";

    #[ORM\Column(name:"telephone", type:"string", length:255,nullable:true)]     
    protected $telephone;

    #[ORM\Column(type:"datetime",nullable:true)]     
    private $date_naiss;

    #[ORM\Column(type:"datetime",nullable:true)]  
    private $dateLastconnection;

    #[ORM\Column(type:"datetime",nullable:true)]     
    private $date_validation;

    #[ORM\Column(type:"datetime",nullable:true)]     
    private $date_inscription;

    #[ORM\Column(type:"datetime",nullable:true)]    
    private $datereinitialisation;

    #[ORM\Column(name:"shortcode", type:"string", length:50,nullable:true)]      
    protected $shortcode;

    #[ORM\Column(name:"token", type:"string",nullable:true)]      
    protected $token;

    #[ORM\Column(name:"oldpwdlist", type:"text", nullable:true)]     
    protected $oldpwdlist;

    #[ORM\Column(name:"nombreenfant", type:"integer",nullable:true)]     
    private $nombreenfant;   

    #[ORM\Column(name:"mobiletelephone", type:"string", length:255,nullable:true)]     
    protected $mobiletelephone;

    #[ORM\Column(name:"nbvisite", type:"integer",nullable:true)]    
    private $nbvisite;

    // #[ORM\OneToMany(targetEntity :Commandemedicaments::class, mappedBy:"patient")]     
    // private $commandemedicaments;

    #[ORM\OneToMany(targetEntity :"App\Entity\Entretiens", mappedBy:"demandeur")]     
    private $entretiens;
    
    #[ORM\ManyToMany(targetEntity:"App\Entity\Programmes")]
    #[ORM\JoinTable(
          name:"patient_programme_table",
          joinColumns:[new JoinColumn(name:"patients_id", referencedColumnName:"id") ] ,
          inverseJoinColumns: [ new JoinColumn(name:"programmes_id", referencedColumnName:"id", unique:false) ]
        )
    ]      
    private $programmes;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $resetToken = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $resetRequestAt = null;
 

    public function __construct() {
       
        $this->date_inscription=new \Datetime("now");
        $this->dateLastconnection=new \Datetime("now");
        $this->enabled = false;
        $this->age = 0;
        $this->nbvisite = 0;        
        $this->rendezvous=new ArrayCollection();
        $this->entretiens = new ArrayCollection();
        $this->programmes = new ArrayCollection();

        // $this->commandemedicaments = new ArrayCollection();
    }
    public function getSlug(){
        return str_replace(" ","-",$this->nom."-".$this->prenom);
    }
    public function getId(){
        return $this->id;
    
    }
    public function jsonSerialize(): array{
        return [            
            'nom' => $this->nom,
            'prenom' => $this->prenom,
            'nomcomplet' => $this->nomComplet,
            'ville'  => $this->ville,
            'telephone'  => $this->telephone, 
            'sexe'  => $this->sexe, 
            'adresse'  => $this->adresse, 
        ];
    } 

    public function setNombreenfant($nombreenfant){
        $this->nombreenfant = $nombreenfant;    
        return $this;
    }

    /**
     * Get nombreenfant
     * @return integer
     */
    public function getNombreenfant(){
        return $this->nombreenfant;
    }

    public function setImageFile($image = null){
      $this->imageFile = $image;       
      if ($image) {
          // if 'updatedAt' is not defined in your entity, use another property
         // $this->date_upd = new \DateTime('now');
      }
    }

    public function getImageFile(){
        return $this->imageFile;
    }

    public function setImage($image){
        $this->image = $image;
    }

    public function getToken(){
        return $this->token;
    }
     public function setToken($image){
        $this->token = $image;
    }
    public function getNbvisite(){
        return $this->nbvisite;
    }
     public function setNbvisite($image){
        $this->nbvisite = $image;
    }

    public function getImage(){
        return $this->image;
    }

     public function setShortcode($image){
        $this->shortcode = $image;
    }

    public function getShortcode(){
        return $this->shortcode;
    }
     public function setOldpwdlist($image){
        $this->oldpwdlist = $image;
    }

    public function getOldpwdlist(){
        return $this->oldpwdlist;
    }
    public function setDatereinitialisation($image){
        $this->datereinitialisation = $image;
    }

    public function getDatereinitialisation(){
        return $this->datereinitialisation;
    }

    public function getRendezvous() {
        return $this->rendezvous;
    }
    public function addRendezvous(Rendezvous $application){
 
        if (!$this->rendezvous->contains($application)) {
            $this->rendezvous[] = $application;
        }
 
    }
    public function removeRendezvous($application){
      $this->rendezvous->removeElement($application);
    }
    
    public function __toString(){
        return (string) $this->nomComplet." ," .$this->ville;
    }    
    
    /**     
     * @param integer $age
     * @return Patients
     */
    public function setAge($age){
        $this->age = $age;    
        return $this;
    }
    /**
     * Set age
     * @param integer $age
     * @return Patients
     */
    public function setStatutMatrimonial($age){
        $this->statutmatrimonial = $age;    
        return $this;
    }

    /**  
     * @return  Dossiermedical
     */
    public function getDossiermedical(){
        return $this->dossiermedical;
    }
    public function setDossiermedical(Dossiermedical $image = null){
        $this->dossiermedical = $image;
    }
    /**
     * Get age 
     * @return integer
     */
    public function getAge(){
        return $this->age;
    }
    /**
     * Get age     *
     * @return string
     */
    public function getStatutMatrimonial(){
        return $this->statutmatrimonial;
    }

     public  function getDateLastconnection(){
        return $this->dateLastconnection;
    }
     public function setDateLastconnection($date){
        $this->dateLastconnection=$date;
    }
    public  function getDateNaiss(){
        return $this->date_naiss;
    }
     public function setDateNaiss($date){
        $this->date_naiss=$date;
    }

    public  function getDateValidation(){
        return $this->date_validation;
    }
    public  function getDateInscription(){
        return $this->date_inscription;
    }
   
    public function setDateValidation($date){
        $this->date_validation=$date;
    }
    public function setDateInscription($date){
        $this->date_inscription=$date;
    }
    public function setNomComplet(string $fullName): void {
        $this->nomComplet = $fullName;
    } 
    // le ? signifie que cela peut aussi retourner null
    public function getNomComplet(){

src/Form/PersonnelsForm.php
<?php

namespace App\Form;

use App\Entity\Personnels;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonnelsForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('image')
            ->add('cv')
            ->add('diplome')
            ->add('specialite')
            ->add('valide')
            ->add('diplomevalide')
            ->add('prixconsultation')
            ->add('nbvisite')
            ->add('nomComplet')
            ->add('sexe')
            ->add('nom')
            ->add('prenom')
            ->add('username')
            ->add('email')
            ->add('password')
            ->add('adresse')
            ->add('zipCode')
            ->add('ville')
            ->add('pays')
            ->add('type')
            ->add('telephone')
            ->add('date_naiss')
            ->add('date_validation')
            ->add('date_inscription')
            ->add('datereinitialisation')
            ->add('dateLastconnection')
            ->add('shortcode')
            ->add('oldpwdlist')
            ->add('token')
            ->add('mobiletelephone')
            ->add('imc')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Personnels::class,
        ]);
    }
}

src/Controller/PersonnelsController.php
<?php

namespace App\Controller;

use App\Entity\Personnels;
use App\Form\PersonnelsForm;
use App\Repository\PersonnelsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/personnels')]
final class PersonnelsController extends AbstractController
{
    #[Route(name: 'app_personnels_index', methods: ['GET'])]
    public function index(PersonnelsRepository $personnelsRepository): Response
    {
        return $this->render('personnels/index.html.twig', [
            'personnels' => $personnelsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_personnels_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $personnel = new Personnels();
        $form = $this->createForm(PersonnelsForm::class, $personnel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($personnel);
            $entityManager->flush();

            return $this->redirectToRoute('app_personnels_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('personnels/new.html.twig', [
            'personnel' => $personnel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_personnels_show', methods: ['GET'])]
    public function show(Personnels $personnel): Response
    {
        return $this->render('personnels/show.html.twig', [
            'personnel' => $personnel,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_personnels_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Personnels $personnel, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PersonnelsForm::class, $personnel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_personnels_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('personnels/edit.html.twig', [
            'personnel' => $personnel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_personnels_delete', methods: ['POST'])]
    public function delete(Request $request, Personnels $personnel, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personnel->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($personnel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_personnels_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/personnels/_delete_form.html.twig
<form method="post" action="{{ path('app_personnels_delete', {'id': personnel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personnel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/personnels/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/personnels/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Personnels{% endblock %}

{% block body %}
    <h1>Edit Personnels</h1>

    {{ include('personnels/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_personnels_index') }}">back to list</a>

    {{ include('personnels/_delete_form.html.twig') }}
{% endblock %}

templates/personnels/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnels index{% endblock %}

{% block body %}
    <h1>Personnels index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Image</th>
                <th>Cv</th>
                <th>Diplome</th>
                <th>Specialite</th>
                <th>Valide</th>
                <th>Diplomevalide</th>
                <th>Prixconsultation</th>
                <th>Nbvisite</th>
                <th>NomComplet</th>
                <th>Sexe</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Username</th>
                <th>Email</th>
                <th>Password</th>
                <th>Adresse</th>
                <th>ZipCode</th>
                <th>Ville</th>
                <th>Pays</th>
                <th>Type</th>
                <th>Telephone</th>
                <th>Date_naiss</th>
                <th>Date_validation</th>
                <th>Date_inscription</th>
                <th>Datereinitialisation</th>
                <th>DateLastconnection</th>
                <th>Shortcode</th>
                <th>Oldpwdlist</th>
                <th>Token</th>
                <th>Mobiletelephone</th>
                <th>Imc</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personnel in personnels %}
            <tr>
                <td>{{ personnel.id }}</td>
                <td>{{ personnel.image }}</td>
                <td>{{ personnel.cv }}</td>
                <td>{{ personnel.diplome }}</td>
                <td>{{ personnel.specialite }}</td>
                <td>{{ personnel.valide ? 'Yes' : 'No' }}</td>
                <td>{{ personnel.diplomevalide ? 'Yes' : 'No' }}</td>
                <td>{{ personnel.prixconsultation }}</td>
                <td>{{ personnel.nbvisite }}</td>
                <td>{{ personnel.nomComplet }}</td>
                <td>{{ personnel.sexe }}</td>
                <td>{{ personnel.nom }}</td>
                <td>{{ personnel.prenom }}</td>
                <td>{{ personnel.username }}</td>
                <td>{{ personnel.email }}</td>
                <td>{{ personnel.password }}</td>
                <td>{{ personnel.adresse }}</td>
                <td>{{ personnel.zipCode }}</td>
                <td>{{ personnel.ville }}</td>
                <td>{{ personnel.pays }}</td>
                <td>{{ personnel.type }}</td>
                <td>{{ personnel.telephone }}</td>
                <td>{{ personnel.dateNaiss ? personnel.dateNaiss|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ personnel.dateValidation ? personnel.dateValidation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ personnel.dateInscription ? personnel.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ personnel.datereinitialisation ? personnel.datereinitialisation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ personnel.dateLastconnection ? personnel.dateLastconnection|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ personnel.shortcode }}</td>
                <td>{{ personnel.oldpwdlist }}</td>
                <td>{{ personnel.token }}</td>
                <td>{{ personnel.mobiletelephone }}</td>
                <td>{{ personnel.imc ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_personnels_show', {'id': personnel.id}) }}">show</a>
                    <a href="{{ path('app_personnels_edit', {'id': personnel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="33">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_personnels_new') }}">Create new</a>
{% endblock %}

templates/personnels/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Personnels{% endblock %}

{% block body %}
    <h1>Create new Personnels</h1>

    {{ include('personnels/_form.html.twig') }}

    <a href="{{ path('app_personnels_index') }}">back to list</a>
{% endblock %}

templates/personnels/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnels{% endblock %}

{% block body %}
    <h1>Personnels</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personnel.id }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ personnel.image }}</td>
            </tr>
            <tr>
                <th>Cv</th>
                <td>{{ personnel.cv }}</td>
            </tr>
            <tr>
                <th>Diplome</th>
                <td>{{ personnel.diplome }}</td>
            </tr>
            <tr>
                <th>Specialite</th>
                <td>{{ personnel.specialite }}</td>
            </tr>
            <tr>
                <th>Valide</th>
                <td>{{ personnel.valide ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Diplomevalide</th>
                <td>{{ personnel.diplomevalide ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Prixconsultation</th>
                <td>{{ personnel.prixconsultation }}</td>
            </tr>
            <tr>
                <th>Nbvisite</th>
                <td>{{ personnel.nbvisite }}</td>
            </tr>
            <tr>
                <th>NomComplet</th>
                <td>{{ personnel.nomComplet }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ personnel.sexe }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ personnel.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ personnel.prenom }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ personnel.username }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ personnel.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ personnel.password }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ personnel.adresse }}</td>
            </tr>
            <tr>
                <th>ZipCode</th>
                <td>{{ personnel.zipCode }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ personnel.ville }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ personnel.pays }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ personnel.type }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ personnel.telephone }}</td>
            </tr>
            <tr>
                <th>Date_naiss</th>
                <td>{{ personnel.dateNaiss ? personnel.dateNaiss|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_validation</th>
                <td>{{ personnel.dateValidation ? personnel.dateValidation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_inscription</th>
                <td>{{ personnel.dateInscription ? personnel.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Datereinitialisation</th>
                <td>{{ personnel.datereinitialisation ? personnel.datereinitialisation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateLastconnection</th>
                <td>{{ personnel.dateLastconnection ? personnel.dateLastconnection|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Shortcode</th>
                <td>{{ personnel.shortcode }}</td>
            </tr>
            <tr>
                <th>Oldpwdlist</th>
                <td>{{ personnel.oldpwdlist }}</td>
            </tr>
            <tr>
                <th>Token</th>
                <td>{{ personnel.token }}</td>
            </tr>
            <tr>
                <th>Mobiletelephone</th>
                <td>{{ personnel.mobiletelephone }}</td>
            </tr>
            <tr>
                <th>Imc</th>
                <td>{{ personnel.imc ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_personnels_index') }}">back to list</a>

    <a href="{{ path('app_personnels_edit', {'id': personnel.id}) }}">edit</a>

    {{ include('personnels/_delete_form.html.twig') }}
{% endblock %}